#!/usr/bin/env bash
# Install nginx
apt-get -y install nginx

# Adjust default homepage
sed -i "21s/^listen .*/listen 80;/" /etc/nginx/sites-enabled/default

# Allow Nginx through the firewall
ufw allow 'Nginx HTTP'

# Write "Hello World!" to the default Nginx homepage
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx service
service nginx restart

