#!/usr/bin/env bash
# Install nginx
apt-get -y install nginx
sed -i "21s/^listen .*/listen 80;/" /etc/nginx/sites-enabled/default
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart

