#!/usr/bin/env bash
# balancer install
sudo apt-get -y update
sudo apt-get install -y haproxy
echo "
frontend marv
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 497142-web-01 52.91.102.19 check
    server 497142-web-02 54.84.252.70 check " >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
